import 'package:blockchain_learning_app/models/lessons_list_model.dart';

class Btn {
  static final List<Lesson> lessons = [
    Lesson("Introduction to Blockchain \nTechnology",
        "lib/images/bitcoin_secure.png", "Lesson 1"),
    Lesson("History and Evolution \nof Blockchain",
        "lib/images/bitcoin_secure.png", "Lesson 2"),
    Lesson("Core Components of a \nBlockchain", "lib/images/bitcoin_secure.png",
        "Lesson 3"),
    Lesson("Cryptography in Blockchain", "lib/images/bitcoin_secure.png",
        "Lesson 4"),
    Lesson("Consensus Mechanisms \nExplained", "lib/images/bitcoin_secure.png",
        "Lesson 5"),
    Lesson("Types of Blockchains", "lib/images/bitcoin_secure.png", "Lesson 6"),
    Lesson("Smart Contracts and Their \nApplications",
        "lib/images/bitcoin_secure.png", "Lesson 7"),
    Lesson("Decentralized Autonomous \nOrganizations (DAOs)",
        "lib/images/bitcoin_secure.png", "Lesson 8"),
    Lesson("Blockchain Security Best \nPractices",
        "lib/images/bitcoin_secure.png", "Lesson 9"),
    Lesson("Privacy and Anonymity in \nBlockchain",
        "lib/images/bitcoin_secure.png", "Lesson 10"),
    Lesson("Interoperability Between \nBlockchains",
        "lib/images/bitcoin_secure.png", "Lesson 11"),
    Lesson("Tokenization and Digital \nAssets", "lib/images/bitcoin_secure.png",
        "Lesson 12"),
    Lesson("Initial Coin Offerings (ICOs) \nand Token Sales",
        "lib/images/bitcoin_secure.png", "Lesson 13"),
    Lesson("Decentralized Finance (DeFi) \nEcosystem",
        "lib/images/bitcoin_secure.png", "Lesson 14"),
    Lesson("Non-Fungible Tokens (NFTs) \nand Their Use Cases",
        "lib/images/bitcoin_secure.png", "Lesson 15"),
    Lesson("Blockchain in Supply Chain \nManagement",
        "lib/images/bitcoin_secure.png", "Lesson 16"),
    Lesson("Blockchain in Healthcare", "lib/images/bitcoin_secure.png",
        "Lesson 17"),
    Lesson("Identity Management on \nthe Blockchain",
        "lib/images/bitcoin_secure.png", "Lesson 18"),
    Lesson("Energy and Sustainability in \nBlockchain",
        "lib/images/bitcoin_secure.png", "Lesson 19"),
    Lesson("Regulatory Challenges and \nCompliance in Blockchain",
        "lib/images/bitcoin_secure.png", "Lesson 20"),
    Lesson("Cross-Border Payments with \nBlockchain",
        "lib/images/bitcoin_secure.png", "Lesson 21"),
    Lesson("Blockchain in Government and \nPublic Services",
        "lib/images/bitcoin_secure.png", "Lesson 22"),
    Lesson("Blockchain in the Internet \nof Things (IoT)",
        "lib/images/bitcoin_secure.png", "Lesson 23"),
    Lesson("Scalability Issues and Solutions \nin Blockchain",
        "lib/images/bitcoin_secure.png", "Lesson 24"),
    Lesson("Oracle Networks and Data Feeds \nin Blockchain",
        "lib/images/bitcoin_secure.png", "Lesson 25"),
    Lesson("Challenges and Future Trends \nin Blockchain",
        "lib/images/bitcoin_secure.png", "Lesson 26"),
    Lesson("Blockchain and Artificial \nIntelligence Integration",
        "lib/images/bitcoin_secure.png", "Lesson 27"),
    Lesson("Case Studies of Successful \nBlockchain Implementations",
        "lib/images/bitcoin_secure.png", "Lesson 28"),
    Lesson("Ethical Considerations in \nBlockchain Development",
        "lib/images/bitcoin_secure.png", "Lesson 29"),
    Lesson("Building a Career in Blockchain: \nSkills and Opportunities",
        "lib/images/bitcoin_secure.png", "Lesson 30"),
  ];
}
